In [81]:
import pandas as pd

In [82]:
feature = pd.read_csv(r"C:\Users\admin\Desktop\Machine Learning\machine-learning-code-orbit\team_members\From Hoor\Data\wallmart\features.csv")
feature

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8185,45,2013-06-28,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,False
8186,45,2013-07-05,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,False
8187,45,2013-07-12,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,False
8188,45,2013-07-19,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,False
8189,45,2013-07-26,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,False

In [83]:
stores = pd.read_csv(r"C:\Users\admin\Desktop\Machine Learning\machine-learning-code-orbit\team_members\From Hoor\Data\wallmart\stores.csv")
stores.head(4)

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863

In [84]:
train = pd.read_csv(r"C:\Users\admin\Desktop\Machine Learning\machine-learning-code-orbit\team_members\From Hoor\Data\wallmart\train.csv")
train

        Store  Dept        Date  Weekly_Sales  IsHoliday
0           1     1  2010-02-05      24924.50      False
1           1     1  2010-02-12      46039.49       True
2           1     1  2010-02-19      41595.55      False
3           1     1  2010-02-26      19403.54      False
4           1     1  2010-03-05      21827.90      False
...       ...   ...         ...           ...        ...
421565     45    98  2012-09-28        508.37      False
421566     45    98  2012-10-05        628.10      False
421567     45    98  2012-10-12       1061.02      False
421568     45    98  2012-10-19        760.01      False
421569     45    98  2012-10-26       1076.80      False

[421570 rows x 5 columns]

##1. Total sales by store

In [85]:
total_sales_by_store = train.groupby('Store')['Weekly_Sales'].sum()
print(total_sales_by_store.sort_values(ascending=False).head())

Store
20    3.013978e+08
4     2.995440e+08
14    2.889999e+08
13    2.865177e+08
2     2.753824e+08
Name: Weekly_Sales, dtype: float64

##2. Total sales by department

In [86]:
total_sales_by_dept = train.groupby('Dept')['Weekly_Sales'].sum()
print(total_sales_by_dept.sort_values(ascending=False).head())

Dept
92    4.839433e+08
95    4.493202e+08
38    3.931181e+08
72    3.057252e+08
90    2.910685e+08
Name: Weekly_Sales, dtype: float64

##3. Average weekly sales by store

In [87]:
avg_sales_by_store = train.groupby('Store')['Weekly_Sales'].mean()
print(avg_sales_by_store.sort_values(ascending=False).head())

Store
20    29508.301592
4     29161.210415
14    28784.851727
13    27355.136891
2     26898.070031
Name: Weekly_Sales, dtype: float64

##4. Total sales by store and department

In [88]:
total_sales_store_dept = train.groupby(['Store', 'Dept'])['Weekly_Sales'].sum().reset_index()
print(total_sales_store_dept.head())

   Store  Dept  Weekly_Sales
0      1     1    3219405.18
1      1     2    6592598.93
2      1     3    1880518.36
3      1     4    5285874.09
4      1     5    3468885.58

##5. Count of weeks recorded per store

In [89]:
weeks_count_per_store = train.groupby('Store')['Date'].count()
print(weeks_count_per_store)

Store
1     10244
2     10238
3      9036
4     10272
5      8999
6     10211
7      9762
8      9895
9      8867
10    10315
11    10062
12     9705
13    10474
14    10040
15     9901
16     9443
17     9864
18     9859
19    10148
20    10214
21     9582
22     9688
23    10050
24    10228
25     9804
26     9854
27    10225
28    10113
29     9455
30     7156
31    10142
32    10202
33     6487
34    10224
35     9528
36     6222
37     7206
38     7362
39     9878
40    10017
41    10088
42     6953
43     6751
44     7169
45     9637
Name: Date, dtype: int64

In [90]:
top_stores = total_sales_by_store.sort_values(ascending=False).head(10)
print(top_stores)

Store
20    3.013978e+08
4     2.995440e+08
14    2.889999e+08
13    2.865177e+08
2     2.753824e+08
10    2.716177e+08
27    2.538559e+08
6     2.237561e+08
1     2.224028e+08
39    2.074455e+08
Name: Weekly_Sales, dtype: float64

## 1. Merge sales (train) with store features (features)

In [91]:

# Merge with stores data on 'Store'
final_data = pd.merge(feature, stores, on='Store', how='left')

print(final_data.head())

   Store        Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0      1  2010-02-05        42.31       2.572        NaN        NaN
1      1  2010-02-12        38.51       2.548        NaN        NaN
2      1  2010-02-19        39.93       2.514        NaN        NaN
3      1  2010-02-26        46.63       2.561        NaN        NaN
4      1  2010-03-05        46.50       2.625        NaN        NaN

   MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday Type  \
0        NaN        NaN        NaN  211.096358         8.106      False    A
1        NaN        NaN        NaN  211.242170         8.106       True    A
2        NaN        NaN        NaN  211.289143         8.106      False    A
3        NaN        NaN        NaN  211.319643         8.106      False    A
4        NaN        NaN        NaN  211.350143         8.106      False    A

     Size
0  151315
1  151315
2  151315
3  151315
4  151315

## Concatenating data

In [92]:
first_week = train[train['Date'] == train['Date'].min()]  # Get the first week of data
second_week = train[train['Date'] == train['Date'].sort_values().unique()[1]]  # Get the second week of data
concatenated_data = pd.concat([first_week, second_week], ignore_index=True) # Concatenate the two weeks of data
concatenated_data.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     2  2010-02-05      50605.27      False
2      1     3  2010-02-05      13740.12      False
3      1     4  2010-02-05      39954.04      False
4      1     5  2010-02-05      32229.38      False

## Basic EDA

In [93]:
train.describe()
train

        Store  Dept        Date  Weekly_Sales  IsHoliday
0           1     1  2010-02-05      24924.50      False
1           1     1  2010-02-12      46039.49       True
2           1     1  2010-02-19      41595.55      False
3           1     1  2010-02-26      19403.54      False
4           1     1  2010-03-05      21827.90      False
...       ...   ...         ...           ...        ...
421565     45    98  2012-09-28        508.37      False
421566     45    98  2012-10-05        628.10      False
421567     45    98  2012-10-12       1061.02      False
421568     45    98  2012-10-19        760.01      False
421569     45    98  2012-10-26       1076.80      False

[421570 rows x 5 columns]

In [94]:
stores.describe()
stores

    Store Type    Size
0       1    A  151315
1       2    A  202307
2       3    B   37392
3       4    A  205863
4       5    B   34875
5       6    A  202505
6       7    B   70713
7       8    A  155078
8       9    B  125833
9      10    B  126512
10     11    A  207499
11     12    B  112238
12     13    A  219622
13     14    A  200898
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
18     19    A  203819
19     20    A  203742
20     21    B  140167
21     22    B  119557
22     23    B  114533
23     24    A  203819
24     25    B  128107
25     26    A  152513
26     27    A  204184
27     28    A  206302
28     29    B   93638
29     30    C   42988
30     31    A  203750
31     32    A  203007
32     33    A   39690
33     34    A  158114
34     35    B  103681
35     36    A   39910
36     37    C   39910
37     38    C   39690
38     39    A  184109
39     40    A  155083
40     41    A  196321
41     42    C   39690
42     43    C   41062
43     44    C   39910
44     45    B  118221

In [95]:
feature.describe()
feature

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8185,45,2013-06-28,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,False
8186,45,2013-07-05,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,False
8187,45,2013-07-12,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,False
8188,45,2013-07-19,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,False
8189,45,2013-07-26,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,False

In [96]:

stores.value_counts()

Store  Type  Size
1      A     151315    1
2      A     202307    1
3      B     37392     1
4      A     205863    1
5      B     34875     1
6      A     202505    1
7      B     70713     1
8      A     155078    1
9      B     125833    1
10     B     126512    1
11     A     207499    1
12     B     112238    1
13     A     219622    1
14     A     200898    1
15     B     123737    1
16     B     57197     1
17     B     93188     1
18     B     120653    1
19     A     203819    1
20     A     203742    1
21     B     140167    1
22     B     119557    1
23     B     114533    1
24     A     203819    1
25     B     128107    1
26     A     152513    1
27     A     204184    1
28     A     206302    1
29     B     93638     1
30     C     42988     1
31     A     203750    1
32     A     203007    1
33     A     39690     1
34     A     158114    1
35     B     103681    1
36     A     39910     1
37     C     39910     1
38     C     39690     1
39     A     184109    1
40     A     155083    1
41     A     196321    1
42     C     39690     1
43     C     41062     1
44     C     39910     1
45     B     118221    1
Name: count, dtype: int64

In [97]:
train.value_counts()
train.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [99]:
feature.value_counts()
feature.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [100]:
train.filter(items=['Store', 'Date', 'Weekly_Sales']).head()

   Store        Date  Weekly_Sales
0      1  2010-02-05      24924.50
1      1  2010-02-12      46039.49
2      1  2010-02-19      41595.55
3      1  2010-02-26      19403.54
4      1  2010-03-05      21827.90

In [101]:
stores.filter(items=['Store', 'Type']).head()

   Store Type
0      1    A
1      2    A
2      3    B
3      4    A
4      5    B

In [102]:
feature.filter(items=['Store', 'Date', 'Temperature']).head()

   Store        Date  Temperature
0      1  2010-02-05        42.31
1      1  2010-02-12        38.51
2      1  2010-02-19        39.93
3      1  2010-02-26        46.63
4      1  2010-03-05        46.50