In [1]:
import pandas as pd

In [2]:
import numpy as np

In [37]:
import matplotlib.pyplot as plt

In [42]:
path= r"C:\Users\admin\Desktop\Machine Learning\machine-learning-code-orbit\team_members\From Hoor\Data1\archive (3)\Student_Performance.csv"
df= pd.read_csv(path, sep = ';')
df

     Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0                                     7,99,Yes,9,1,91.0
1                                      4,82,No,4,2,65.0
2                                     8,51,Yes,7,2,45.0
3                                     5,52,Yes,5,2,36.0
4                                      7,75,No,8,5,66.0
...                                                 ...
9995                                  1,49,Yes,4,2,23.0
9996                                  7,64,Yes,8,5,58.0
9997                                  6,83,Yes,8,5,74.0
9998                                  9,97,Yes,7,0,95.0
9999                                   7,74,No,8,1,64.0

[10000 rows x 1 columns]

In [6]:
print("Dataset shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nData types:\n", df.dtypes)
print("\nStatistical Summary:\n", df.describe())

Dataset shape: (10000, 1)

Missing values:
 Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index    0
dtype: int64

Data types:
 Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index    object
dtype: object

Statistical Summary:
        Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
count                                               10000
unique                                               9873
top                                     5,59,Yes,9,0,45.0
freq                                                    3

## Preprocessing

In [ ]:
#Encode categorical variables
df = pd.get_dummies(df, drop_first=True)
df.head()

,"Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,4,8,12.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,6,13.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,9,10.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,9,14.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,0,15.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,3,12.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,6,16.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,7,4,11.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,7,4,14.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,8,5,16.0",...,"Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,No,8,7,95.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,No,9,4,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,4,8,97.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,4,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,6,97.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,7,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,7,5,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,1,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,6,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,8,100.0"
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
df.dropna(inplace=True)
df.head()

,"Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,4,8,12.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,6,13.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,9,10.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,5,9,14.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,0,15.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,3,12.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,6,6,16.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,7,4,11.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,7,4,14.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_1,40,No,8,5,16.0",...,"Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,No,8,7,95.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,No,9,4,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,4,8,97.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,4,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,6,97.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,5,7,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,7,5,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,1,99.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,6,98.0","Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index_9,99,Yes,8,8,100.0"
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [44]:
df.isnull().sum()

Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index    0
dtype: int64

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                   --------------  -----
 0   Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index  10000 non-null  object
dtypes: object(1)
memory usage: 78.3+ KB

In [46]:
df.columns

Index(['Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index'], dtype='object')

In [49]:
df.head()

  Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0                                  7,99,Yes,9,1,91.0
1                                   4,82,No,4,2,65.0
2                                  8,51,Yes,7,2,45.0
3                                  5,52,Yes,5,2,36.0
4                                   7,75,No,8,5,66.0

In [50]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index]
Index: []

In [51]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index]
Index: []

In [52]:
df.isnull().sum()

Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index    0
dtype: int64

In [55]:
df[df.astype(str).apply(lambda x: x.str.contains('\?')).any(axis=1)]

<>:1: SyntaxWarning: invalid escape sequence '\?'
<>:1: SyntaxWarning: invalid escape sequence '\?'
C:\Users\admin\AppData\Local\Temp\ipykernel_21476\901282791.py:1: SyntaxWarning: invalid escape sequence '\?'
  df[df.astype(str).apply(lambda x: x.str.contains('\?')).any(axis=1)]

Empty DataFrame
Columns: [Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index]
Index: []

In [67]:
df.to_csv('clean.csv')
df.head()

,Hours_Studied,Previous_Scores,Sleep_Hours,Sample_Question_Papers_Practiced,Performance_Index,Extracurricular_Activities_Yes
0,7,99,9,1,91.0,True
1,4,82,4,2,65.0,False
2,8,51,7,2,45.0,True
3,5,52,5,2,36.0,True
4,7,75,8,5,66.0,False

## Data Overview

In [69]:
df.isnull().sum()

Hours_Studied                       0
Previous_Scores                     0
Sleep_Hours                         0
Sample_Question_Papers_Practiced    0
Performance_Index                   0
Extracurricular_Activities_Yes      0
dtype: int64

## Check for Missing Values

In [70]:
df.duplicated().sum()

np.int64(127)

## Check for Duplicate Rows

In [71]:
df.shape

(10000, 6)

## Preview the Data

In [73]:
df.corr()

,Hours_Studied,Previous_Scores,Sleep_Hours,Sample_Question_Papers_Practiced,Performance_Index,Extracurricular_Activities_Yes
Hours_Studied,1.000000,-0.012390,0.001245,0.017463,0.373730,0.003873
Previous_Scores,-0.012390,1.000000,0.005944,0.007888,0.915189,0.008369
Sleep_Hours,0.001245,0.005944,1.000000,0.003990,0.048106,-0.023284
Sample_Question_Papers_Practiced,0.017463,0.007888,0.003990,1.000000,0.043268,0.013103
Performance_Index,0.373730,0.915189,0.048106,0.043268,1.000000,0.024525
Extracurricular_Activities_Yes,0.003873,0.008369,-0.023284,0.013103,0.024525,1.000000

## Scalling

In [ ]:
X = df.drop('Performance Index', axis=1)
y = df['Performance Index']

## Split Data into Training and Testing Sets

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

## Initialize Linear Regression Model

In [ ]:

regressor.fit(X_train,y_train)

## Train Linear Regression Model

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = regressor.predict(X_test)

## Predict and Prepare for Evaluation

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("--- Linear Regression Results ---")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

In [ ]:
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red', linestyle='--')
plt.title('Linear Regression Predicted Performance Index')
plt.xlabel('Actual Performance Index')
plt.ylabel('Predicted Performance Index')
plt.grid()
plt.show()