In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load your CSV file
path = r"C:\Users\admin\Desktop\archive (1)\laptopData.csv"
df= pd.read_csv(path)
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [18]:
# Step 1: Drop any unneeded index column (like 'Unnamed: 0')
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_Brand
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,Intel
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB SSD,Intel HD Graphics 6000,macOS,1.34,47895.5232,Intel
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,Intel
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,Intel
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400,Intel
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200,Intel
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB SSD,Intel HD Graphics,Windows 10,1.50,12201.1200,Intel
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,Intel
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200,Intel

In [19]:
# Step 2: Handle missing values and invalid entries
df = df.replace('?', np.nan)  # Replace '?' with NaN
df = df.dropna()              # Drop rows with missing data
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_Brand
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,Intel
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB SSD,Intel HD Graphics 6000,macOS,1.34,47895.5232,Intel
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,Intel
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,Intel
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400,Intel
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200,Intel
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB SSD,Intel HD Graphics,Windows 10,1.50,12201.1200,Intel
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,Intel
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200,Intel

In [22]:
# Step 3: Convert 'Ram' column from "8GB" to integer
df['Ram'] = df['Ram'].astype(str).str.replace('GB', '', regex=False).astype(int)

In [10]:
# Step 4: Convert 'Weight' from "2.1kg" to float
df['Weight'] = df['Weight'].str.replace('kg', '', regex=False)
df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce')  # convert to float
df = df.dropna(subset=['Weight'])  # drop rows with invalid weight

In [11]:
# Step 5: Convert 'Inches' to float
df['Inches'] = df['Inches'].astype(float)

# Step 6: Extract CPU brand (first word of the CPU string)
df['Cpu_Brand'] = df['Cpu'].apply(lambda x: x.split()[0])

In [13]:
# Step 7: Clean the 'Memory' column to split into SSD and HDD

# Normalize memory labels
df['Memory'] = df['Memory'].str.replace('Flash Storage', 'SSD')
df['Memory'] = df['Memory'].str.replace('Hybrid', 'HDD')

In [ ]:
def extract_storage(mem_str): 
    ssd = 0
    hdd = 0
    if pd.isna(mem_str):
        return pd.Series([ssd, hdd])

    parts = mem_str.split('+')
    for part in parts:
        part = part.strip()
        if 'SSD' in part:
            value = part.replace('SSD', '').replace('GB', '').replace('TB', '')
            if 'TB' in part:
                ssd += float(value.strip()) * 1000
            else:
                ssd += float(value.strip())
        elif 'HDD' in part:
            value = part.replace('HDD', '').replace('GB', '').replace('TB', '')
            if 'TB' in part:
                hdd += float(value.strip()) * 1000
            else:
                hdd += float(value.strip())
    return pd.Series([int(ssd), int(hdd)])

# Apply it safely to the column
df[['SSD', 'HDD']] = df['Memory'].apply(extract_storage)
df = df.drop(columns=['Memory'])

In [25]:
# ✅ Final cleaned data ready
print("✅ Data cleaned successfully!")
print(df.head())

✅ Data cleaned successfully!
  Company   TypeName  Inches                    ScreenResolution  \
0   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600
1   Apple  Ultrabook    13.3                            1440x900
2      HP   Notebook    15.6                   Full HD 1920x1080
3   Apple  Ultrabook    15.4  IPS Panel Retina Display 2880x1800
4   Apple  Ultrabook    13.3  IPS Panel Retina Display 2560x1600

                          Cpu  Ram                           Gpu  OpSys  \
0        Intel Core i5 2.3GHz    8  Intel Iris Plus Graphics 640  macOS
1        Intel Core i5 1.8GHz    8        Intel HD Graphics 6000  macOS
2  Intel Core i5 7200U 2.5GHz    8         Intel HD Graphics 620  No OS
3        Intel Core i7 2.7GHz   16            AMD Radeon Pro 455  macOS
4        Intel Core i5 3.1GHz    8  Intel Iris Plus Graphics 650  macOS

   Weight        Price Cpu_Brand  SSD  HDD
0    1.37   71378.6832     Intel  128    0
1    1.34   47895.5232     Intel  128    0
2    1.86   30636.0000     Intel  256    0
3    1.83  135195.3360     Intel  512    0
4    1.37   96095.8080     Intel  256    0

In [15]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price', 'Cpu_Brand'],
      dtype='object')